# The URL the site will be built for
base_url = "https://thequacklife.art"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zhuia"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# The max-width of the page content
grid_size = "grid-lg"

# Whether to enable KaTeX or not
katex = true

# Default author for articles
author = "Gosia"

show_author = true
show_tags = true
show_categories = true
read_more_prompt = "Czytaj więcej"
read_post_prompt = "Czytaj"

# Menu
logo_image = "./logo.png"

hamburger_menu = true

# Menu items to display. You define a url and the name of the menu item.
# NOTE: `$BASE_URL/` must be included in the url name.
main_menu = [
              {url="/", name="Home"},
              {url="/o-mnie", name="O mnie"},
              {url="/kontakt", name="Kontakt"},
]

# Footer

footer_tagline = "Copyright © TheQuackLife"

# Social media buttons to display. You define a url and the name of the platform.
social_links = [
    # {url = "https://t.me/zwitterio", name = "telegram"},
    # {url = "https://twitter.com/gicrisf", name = "twitter"},
    # {url = "https://github.com/gicrisf", name = "github"},
    # {url = "", name = "instagram"},
    # {url = "", name = "facebook"},
    # {url = "", name = "bookstack"},
    # {url = "", name = "dokuwiki"},
]


[extra.sidebar]
# Enable/Disable sidebar
active=true

# Include a text snippet in the sidebar
# You can format it with HTML
text_snippet=""

# Author card
author_bio = "Me życiowe rozterki

I try to understand my life, feelings and emotions"
author_avatar = "avatar.png"

# Include search bar
# TODO template

# Embed twitter iframe in the sidebar


popular_tags=false
archive=false
related_posts=false #TODO

